# Generated by Django 4.2.7 on 2023-11-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='User')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'User',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_disabled', models.BooleanField(default=False)),
                ('token', models.TextField(max_length=10, verbose_name='Token')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'db_table': 'Auth',
                'indexes': [models.Index(fields=['token'], name='auth_token_idx')],
            },
        ),
    ]
